# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyX1XMgEA1JXTgRMteZnFdxe2hS4tp3K
"""

<img src="https://i.imgur.com/49FNOHj.jpg">

"""<img src="https://i.imgur.com/49FNOHj.jpg">

"""

import pandas as pd
import matplotlib.pyplot as plt
colors_df = pd.read_csv("data/colors.csv")
colors_df.head(20)

colors_df['name'].nunique()

colors_df.groupby('is_trans').count()

colors_df.is_trans.value_counts()

"""### Understanding LEGO Themes vs LEGO Sets

Walk into lego store and you will see their products organised by their products organised by theme. Their themes include Batman, Star Wars, Harry Potter and many many more.
<img src="https://i.imgur.com/aKcwkSx.png">

A lego **set** is particular box of LEGO or product. Therefore, a single theme typically has many diffrent sets.
<img src="https://i.imgur.com/whB1olq.png">
"""

sets_df = pd.read_csv("data/sets.csv")
sets_df.head()

oldest_set = sets_df['year'].idxmin()
sets_df.loc[oldest_set]

set_list = sets_df.groupby('year').count()
set_list

set_list.columns

highest_element_seats = sets_df.sort_values(by='num_parts', ascending=False)
highest_element_seats.head()

plt.plot(set_list.index[:-2], set_list.name[:-2])

themes_by_year = sets_df.groupby('year').agg({'theme_id':pd.Series.nunique})
themes_by_year.rename(columns = {'theme_id':'nr_themes'}, inplace=True)
themes_by_year

themes_by_year.tail()

ax1 = plt.gca()
ax2 = ax1.twinx()

ax2.plot(themes_by_year.index[:-2], themes_by_year.nr_themes[:-2], color='g')
ax1.plot(set_list.index[:-2], set_list.name[:-2], 'b')

ax1.set_xlabel('Year')
ax1.set_ylabel('Numbers of sets', color='g')
ax2.set_ylabel('Numbers of Themes', color='b')

parts_per_set = sets_df.groupby('year').agg({'num_parts':pd.Series.mean})
parts_per_set.rename(columns = {'num_parts':'average_num_parts'}, inplace=True)
parts_per_set

plt.scatter(parts_per_set.index, parts_per_set.average_num_parts)

set_theme_count = sets_df['theme_id'].value_counts()
set_theme_count[:5]

"""<img src="https://i.imgur.com/Sg4lcjx.png">"""

themes_df = pd.read_csv('data/themes.csv')
themes_df.head(20)

themes_df[themes_df.name == 'Star Wars']

sets_df[sets_df.theme_id == 18]

set_theme_count = pd.DataFrame({'id':set_theme_count.index,
                                'set_count':set_theme_count.values})
# set_theme_count.rename(columns = {'values':'set_count'}, inplace=True)
                              

set_theme_count

merged_df = pd.merge(set_theme_count, themes_df, on='id')

merged_df

plt.figure(figsize=(14,8))
plt.xticks(fontsize=14, rotation=45)
plt.yticks(fontsize=14)
plt.ylabel('Nr of Sets', fontsize=14)
plt.xlabel('Theme Name', fontsize=14)
plt.bar(merged_df.name[:10], merged_df.set_count[:10])